apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: dev-deployment
build:
  artifacts:
    - image: custom-sms
      context: sms/
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/namespace.yaml
      - k8s/sms.yaml
      - k8s/vault-pv.yaml
      - k8s/vault.yaml
      - k8s/vault-pvc.yaml
  # helm:
  #   releases:
  #     - name: vault
  #       chartPath: helm/vault
  #       valuesFiles:
  #         - helm/vault/values.yaml
  #       setValues:
  #         server.ha.enabled: "false"
  #       namespace: vault
  #       createNamespace: true
portForward:
  - resourceType: service
    resourceName: sms-service
    namespace: sms
    port: 8082
  - resourceType: service
    resourceName: vault-service
    namespace: vault
    port: 8200
    localPort: 8200
profiles:
  - name: dev
    build:
      artifacts:
        - image: sms
          context: sms/
          docker:
            dockerfile: Dockerfile
    deploy:
      # helm:
      #   releases:
      #     - name: vault
      #       chartPath: helm/vault
      #       valuesFiles:
      #         - helm/vault/values.yaml
      kubectl:
        manifests:
          - k8s/namespace.yaml
          - k8s/sms.yaml
          - k8s/vault-pv.yaml
          - k8s/vault-pvc.yaml
          - k8s/vault.yaml
