apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
  namespace: netbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbox
  template:
    metadata:
      labels:
        app: netbox
    spec:
      containers:
        - name: netbox
          image: netboxcommunity/netbox:latest
          env:
            - name: SUPERUSER_EMAIL
              value: "admin@example.com"
            - name: SUPERUSER_PASSWORD
              value: "admin"
            - name: ALLOWED_HOSTS
              value: "*"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: netbox-service
  namespace: netbox
spec:
  selector:
    app: netbox
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081
  type: NodePort
