apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms
  namespace: sms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms
  template:
    metadata:
      labels:
        app: sms
    spec:
      containers:
        - name: sms
          image: custom-sms
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: sms-service
  namespace: sms
spec:
  selector:
    app: sms
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
