apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      securityContext:
        fsGroup: 1000  # Ensures write permissions for the Vault container
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-pvc
        - name: config-volume
          configMap:
            name: vault-config
      containers:
        - name: vault
          image: hashicorp/vault:latest
          args:
            - "server"
            - "-config=/vault/config/config.hcl"
          env:
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
          ports:
            - containerPort: 8200
          securityContext:
            runAsUser: 1000  # Vault runs as user 1000
            runAsGroup: 1000  # Ensures Vault has group access
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data  # Writable volume for Vault data
            - name: config-volume
              mountPath: /vault/config  # Read-only volume for the config
              readOnly: true  # Explicitly setting read-only for config
      initContainers:
        - name: vault-init
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Fixing permissions for Vault data..."
              chown -R 1000:1000 /vault/data
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data  # Only modifying /vault/data directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  config.hcl: |
    storage "raft" {
      path    = "/vault/data"
      node_id = "node1"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = "true"
    }

    ui = true
