server:
  ha:
    enabled: false

  dataStorage:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    existingClaim: vault-pvc

  extraVolumes:
    - name: vault-storage
      persistentVolumeClaim:
        claimName: vault-pvc

  extraVolumeMounts:
    - name: vault-storage
      mountPath: /vault/data

  extraInitContainers:
    - name: vault-init
      image: hashicorp/vault:latest
      command:
        - "sh"
        - "-c"
        - |
          export VAULT_ADDR=http://127.0.0.1:8200
          if [ ! -f /vault/data/init.json ]; then
            echo "Initializing Vault..."
            vault operator init -format=json > /vault/data/init.json
          fi
          echo "Unsealing Vault..."
          UNSEAL_KEYS=$(cat /vault/data/init.json | jq -r '.unseal_keys_b64[]')
          for key in $UNSEAL_KEYS; do
            vault operator unseal $key
          done
